# Generated by Django 5.0 on 2024-09-12 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title', 'subtitle'], name='news_articl_title_5e48d2_idx'),
        ),
    ]
